//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
 //click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
import java.util.Scanner;
public class Main {
    public static void main(String[] args) {
        Scanner scanner=new Scanner(System.in);
        String name1,name2,name3,name4,name5,reg1,reg2,reg3,reg4,reg5;
        int marks1_1,marks1_2,marks1_3,marks1_4,marks1_5,marks1_6,marks1_7;
        int marks2_1,marks2_2,marks2_3,marks2_4,marks2_5,marks2_6,marks2_7;
        int marks3_1,marks3_2,marks3_3,marks3_4,marks3_5,marks3_6,marks3_7;
        int marks4_1,marks4_2,marks4_3,marks4_4,marks4_5,marks4_6,marks4_7;
        int marks5_1,marks5_2,marks5_3,marks5_4,marks5_5,marks5_6,marks5_7;
        System.out.print("First student registration number");
        reg1=scanner.nextLine();
        System.out.print("First student name");
        name1=scanner.nextLine();
        System.out.print("First student marks for CCS 2201");
        marks1_1=scanner.nextInt();
        System.out.print("First student marks for CCS 2202");
        marks1_2=scanner.nextInt();
        System.out.print("First student marks for CCS 2203");
        marks1_3=scanner.nextInt();
        System.out.print("First student marks for CCS 2204");
        marks1_4=scanner.nextInt();
        System.out.print("First student marks for CCS 2205");
        marks1_5=scanner.nextInt();
        System.out.print("First student marks for CCS 2206");
        marks1_6=scanner.nextInt();
        System.out.print("First student marks for CCS 2207");
        marks1_7=scanner.nextInt();
        System.out.print("Second student registration number");
        scanner.nextLine();
        reg2=scanner.nextLine();
        System.out.print("Second student name");
        name2=scanner.nextLine();
        System.out.print("Second student marks for CCS 2201");
        marks2_1=scanner.nextInt();
        System.out.print("Second student marks for CCS 2202");
        marks2_2=scanner.nextInt();
        System.out.print("Second student marks for CCS 2203");
        marks2_3=scanner.nextInt();
        System.out.print("Second student marks for CCS 2204");
        marks2_4=scanner.nextInt();
        System.out.print("Second student marks for CCS 2205");
        marks2_5=scanner.nextInt();
        System.out.print("Second student marks for CCS 2206");
        marks2_6=scanner.nextInt();
        System.out.print("Second student marks for CCS 2207");
        marks2_7=scanner.nextInt();
       System.out.print("Third student registration number");
        scanner.nextLine();
        reg3=scanner.nextLine();
        System.out.print("Third student name");
        name3=scanner.nextLine();
        System.out.print("Third student marks for CCS 2201");
        marks3_1=scanner.nextInt();
        System.out.print("Third student marks for CCS 2202");
        marks3_2=scanner.nextInt();
        System.out.print("Third student marks for CCS 2203");
        marks3_3=scanner.nextInt();
        System.out.print("Third student marks for CCS 2204");
        marks3_4=scanner.nextInt();
        System.out.print("Third student marks for CCS 2205");
        marks3_5=scanner.nextInt();
        System.out.print("Third student marks for CCS 2206");
        marks3_6=scanner.nextInt();
        System.out.print("Third student marks for CCS 2207");
        marks3_7=scanner.nextInt();
        System.out.print("Fourth student registration number");
        scanner.nextLine();
        reg4=scanner.nextLine();
        System.out.print("Fourth student name");
        name4=scanner.nextLine();
        System.out.print("Fourth student marks for CCS 2201");
        marks4_1=scanner.nextInt();
        System.out.print("Fourth student marks for CCS 2202");
        marks4_2=scanner.nextInt();
        System.out.print("Fourth student marks for CCS 2203");
        marks4_3=scanner.nextInt();
        System.out.print("Fourth student marks for CCS 2204");
        marks4_4=scanner.nextInt();
        System.out.print("Fourth student marks for CCS 2205");
        marks4_5=scanner.nextInt();
        System.out.print("Fourth student marks for CCS 2206");
        marks4_6=scanner.nextInt();
        System.out.print("Fourth student marks for CCS 2207");
        marks4_7=scanner.nextInt();
        System.out.print("Fifth student registration number");
        scanner.nextLine();
        reg5=scanner.nextLine();
        System.out.print("Fifth student name");
        name5=scanner.nextLine();
        System.out.print("Fifth student marks for CCS 2201");
        marks5_1=scanner.nextInt();
        System.out.print("Fifth student marks for CCS 2202");
        marks5_2=scanner.nextInt();
        System.out.print("Fifth student marks for CCS 2203");
        marks5_3=scanner.nextInt();
        System.out.print("Fifth student marks for CCS 2204");
        marks5_4=scanner.nextInt();
        System.out.print("Fifth student marks for CCS 2205");
        marks5_5=scanner.nextInt();
        System.out.print("Fifth student marks for CCS 2206");
        marks5_6=scanner.nextInt();
        System.out.print("Fifth student marks for CCS 2207");
        marks5_7=scanner.nextInt();/**/
        float total1=marks1_1+marks1_2+marks1_3+marks1_4+marks1_5+marks1_6+marks1_7,average1=total1/7;
        float total2=marks2_1+marks2_2+marks2_3+marks2_4+marks2_5+marks2_6+marks2_7,average2=total2/7;
        float total3=marks3_1+marks3_2+marks3_3+marks3_4+marks3_5+marks3_6+marks3_7,average3=total3/7;
        float total4=marks4_1+marks4_2+marks4_3+marks4_4+marks4_5+marks4_6+marks4_7,average4=total4/7;
        float total5=marks5_1+marks5_2+marks5_3+marks5_4+marks5_5+marks5_6+marks5_7,average5=total5/7;
        System.out.println("                                          Dedan Kimathi University of Technology");
        System.out.println("                                            School of Computer Science and IT");
        System.out.println("                                             Department of Computer Science");
        System.out.println("                                                Academic year:2024/2025");
        System.out.println("                                         STUDENT MARKSHEET(SECOND YEAR RESULTS)");

        System.out.println("Students score sheet");
        System.out.println("-----------------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println("Reg No.\t\t\t\tFull Name\t\tCCS 2201\tCCS 2202\tCCS 2203\tCCS 2204\tCCS 2205\tCCS 2206\tCCS 2207\tTOTALS\tAVERAGE\tSTATUS\tGRADE");
        System.out.println("-----------------------------------------------------------------------------------------------------------------------------------------------------");
        System.out.println(reg1+"\t"+name1+"\t"+marks1_1+"\t\t\t"+marks1_2+"\t\t\t"+marks1_3+"\t\t\t"+marks1_4+"\t\t\t"+marks1_5+"\t\t\t"+marks1_6+"\t\t\t"+marks1_7+"\t\t\t"+total1+"\t"+average1+"\t\t\t");
        System.out.println(reg2+"\t"+name2+"\t"+marks2_1+"\t\t\t"+marks2_2+"\t\t\t"+marks2_3+"\t\t\t"+marks2_4+"\t\t\t"+marks2_5+"\t\t\t"+marks2_6+"\t\t\t"+marks2_7+"\t\t\t"+total2+"\t"+average2+"\t\t\t");
        System.out.println(reg3+"\t"+name3+"\t"+marks3_1+"\t\t\t"+marks3_2+"\t\t\t"+marks3_3+"\t\t\t"+marks3_4+"\t\t\t"+marks3_5+"\t\t\t"+marks3_6+"\t\t\t"+marks3_7+"\t\t\t"+total3+"\t"+average3+"\t\t\t");
        System.out.println(reg4+"\t"+name4+"\t"+marks4_1+"\t\t\t"+marks4_2+"\t\t\t"+marks4_3+"\t\t\t"+marks4_4+"\t\t\t"+marks4_5+"\t\t\t"+marks4_6+"\t\t\t"+marks4_7+"\t\t\t"+total4+"\t"+average4+"\t\t\t");
        System.out.println(reg5+"\t"+name5+"\t"+marks5_1+"\t\t\t"+marks5_2+"\t\t\t"+marks5_3+"\t\t\t"+marks5_4+"\t\t\t"+marks5_5+"\t\t\t"+marks5_6+"\t\t\t"+marks5_7+"\t\t\t"+total5+"\t"+average5+"\t\t\t");
        System.out.println("-----------------------------------------------------------------------------------------------------------------------------------------------------");
        }
    }
